import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import { useState } from "react";
import AuthWrapper from "../components/authWrapper";

const Signup: NextPage = () => {
  const router = useRouter();
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [confirmPwd, setConfirmPwd] = useState("");

  const handleSignup = () => {
    if (password != confirmPwd) {
      return alert("Passwords doesn't match! Please try again");
    } else {
      return alert("Firebase sign up to be implemented:) ");
    }
  };

  return (
    <AuthWrapper>
      <div className=''>
        <Head>
          <title>Create Next App</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <div className='text-center'>
          <h3 className='text-bold'>Login</h3>
          <input
            type='text'
            name='email'
            id='email'
            placeholder='Eter email'
            value={email}
            onChange={(e) => setEmail(e.target.value)}
          />
          <br />
          <input
            type='password'
            name='password'
            id='password'
            value={password}
            placeholder='Enter password'
            onChange={(e) => setPassword(e.target.value)}
          />
          <br />
          <input
            type='password'
            name='confirmPwd'
            id='confirmPwd'
            value={confirmPwd}
            placeholder='Confirm password'
            onChange={(e) => setConfirmPwd(e.target.value)}
          />
        </div>
        <button
          onClick={handleSignup}
          className='p-2 text-bold bg-orange-400 rounded'
        >
          Sign Up
        </button>
        <br />
        <Link href='/login'>
          <a className='text-blue-600 underline'>
            Already have an account? Login
          </a>
        </Link>
      </div>
    </AuthWrapper>
  );
};

export default Signup;
